server:
  port: 8000

spring:
  application:
    name: api-gateway-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
      gateway:
        routes:
          - id: user-service # User-service Login
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/login
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie # Post로 전달되는 Login정보는 매 번 초기화
              - RewritePath=/user-service/(?<segment>.*), /$\{segment} # 해당하는 서비스로 포워딩 시 uri를 변경 /user-service/login -> /login
          - id: user-service # User-service Join
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/users
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id: user-service # user-service etc
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/**
              - Method=GET
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
              - AuthorizationHeaderFilter # 인증 필터
          - id: user-service # actuator routing
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user-service/actuator/**
              - Method=GET,POST
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/user-service/(?<segment>.*), /$\{segment}
          - id: catalog-service
            uri: lb://CATALOG-SERVICE
            predicates:
              Path=/catalog-service/**
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              Path=/order-service/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


token:
  secret: user_token
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
