
server:
  port: 8761 # Eureka Server 포트 설정
spring:
  application:
    name: discoveryservice # Microservice의 고유ID

# 외부 다른 마이크로서비스와 정보를 주고받을 필요는 없기 때문에 자기 자신은 등록하지 않는다.
# 자기 자신을 마이크로서비스로 등록하지 않는 것.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
